apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external
  namespace: default
subsets:
  - addresses:
    - ip: 10.98.12.24 #外部数据库地址
    ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-external
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP

